export const BUTTON_CLICKED_SUCCESS = 'BUTTON_CLICKED_SUCCESS';
export const BUTTON_CLICKED_REQUEST = 'BUTTON_CLICKED_REQUEST';
export const BUTTON_CLICKED_FAILURE = 'BUTTON_CLICKED_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_SUCCESS';

export const CONFIRMATION_REQUEST = 'CONFIRMATION_REQUEST';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const CONFIRMATION_FAILURE = 'CONFIRMATION_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
